name: conv_onet
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - cython
  - imageio
  - numpy
  - numpy-base
  - matplotlib
  - matplotlib-base
  - pandas
  - pillow
  - pytest
  - python=3.9
  - pytorch
  - pyyaml
  - scikit-image
  - scipy
  - tensorboardx
  - torchvision
  - tqdm
  - trimesh
  - pip:
    - pyembree
    - h5py
    - plyfile
    - torch_scatter
