method: conv_onet
data:
  input_type: partial_pointcloud
  classes: [""]
  path: /cluster/project/infk/courses/252-0579-00L/group20/SHARP_data_convonet/track1/train_partial
  train_split: train
  val_split: val
  # pointcloud_chamfer_file: points
  pointcloud_file: points.npz
  points_file: points.npz
  points_iou_file: points.npz
  pointcloud_n: 3000
  pointcloud_noise: 0
  #points_subsample: 1024
  voxels_file: null
  #unit_size: 0.005 # size of a voxel
  points_unpackbits: false
model:
  encoder: pointnet_local_pool
  encoder_kwargs:
    hidden_dim: 32
    plane_type: 'grid'
    grid_resolution: 32
    unet3d: True
    unet3d_kwargs:
      num_levels: 3
      f_maps: 32
      in_channels: 32
      out_channels: 32
  decoder: simple_local      
  decoder_kwargs:
    sample_mode: bilinear # bilinear / nearest
    hidden_size: 32
  c_dim: 32
training:
  out_dir: out/SHARP_training_grid32
  batch_size: 32
  model_selection_metric: iou
  model_selection_mode: maximize
  print_every: 100
  visualize_every: 10000
  validate_every: 1000 # TODO: validation for crop training
  checkpoint_every: 2000
  backup_every: 10000
  n_workers: 8
  n_workers_val: 4
